# Generated by Django 5.1.4 on 2024-12-23 18:12

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default_user_image.png', upload_to=users.models.user_image_upload_to),
        ),
    ]
