# Generated by Django 5.1.4 on 2024-12-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Community',
            new_name='community',
        ),
    ]
