# Generated by Django 5.1.4 on 2024-12-23 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_rename_community_post_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='posts',
        ),
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(default='default_community_image.jpeg', upload_to='communities_images/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='member_of_communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
