# Generated by Django 5.1.4 on 2025-01-07 03:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_alter_like_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'post'], name='communities_user_id_37fd73_idx'),
        ),
    ]
