# Generated by Django 5.1.4 on 2024-12-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_alter_community_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='posts',
            field=models.ManyToManyField(related_name='community_posts', to='communities.post'),
        ),
    ]
