# Generated by Django 5.1.4 on 2024-12-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_alter_post_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='posts',
        ),
    ]
