--
-- PostgreSQL database dump
--

-- Dumped from database version 14.15 (Ubuntu 14.15-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.15 (Ubuntu 14.15-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO goodreads_clone_dev;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO goodreads_clone_dev;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO goodreads_clone_dev;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: books_author; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.books_author (
    id bigint NOT NULL,
    name character varying(128) NOT NULL,
    birth_date date NOT NULL,
    death_date date,
    bio text,
    photo character varying(100) NOT NULL,
    added_date timestamp with time zone NOT NULL,
    slug character varying(128)
);


ALTER TABLE public.books_author OWNER TO goodreads_clone_dev;

--
-- Name: books_author_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.books_author ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_author_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: books_book; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.books_book (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    buy_link character varying(255),
    description text NOT NULL,
    pages integer NOT NULL,
    publication_date date NOT NULL,
    added_date timestamp with time zone NOT NULL,
    cover character varying(100) NOT NULL,
    avg_rating numeric(3,2) NOT NULL,
    author_id bigint,
    slug character varying(255),
    CONSTRAINT books_book_pages_check CHECK ((pages >= 0))
);


ALTER TABLE public.books_book OWNER TO goodreads_clone_dev;

--
-- Name: books_book_genres; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.books_book_genres (
    id bigint NOT NULL,
    book_id bigint NOT NULL,
    genre_id bigint NOT NULL
);


ALTER TABLE public.books_book_genres OWNER TO goodreads_clone_dev;

--
-- Name: books_book_genres_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.books_book_genres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_book_genres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: books_book_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.books_book ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_book_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: books_bookreview; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.books_bookreview (
    id bigint NOT NULL,
    content text NOT NULL,
    rating smallint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    book_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT books_bookreview_rating_check CHECK ((rating >= 0))
);


ALTER TABLE public.books_bookreview OWNER TO goodreads_clone_dev;

--
-- Name: books_bookreview_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.books_bookreview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_bookreview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: books_genre; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.books_genre (
    id bigint NOT NULL,
    name character varying(128) NOT NULL,
    description text,
    added_date timestamp with time zone NOT NULL
);


ALTER TABLE public.books_genre OWNER TO goodreads_clone_dev;

--
-- Name: books_genre_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.books_genre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_genre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: communities_comment; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.communities_comment (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    post_id bigint NOT NULL
);


ALTER TABLE public.communities_comment OWNER TO goodreads_clone_dev;

--
-- Name: communities_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.communities_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.communities_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: communities_community; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.communities_community (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    date_added timestamp with time zone NOT NULL,
    image character varying(100) NOT NULL,
    owner_id bigint NOT NULL
);


ALTER TABLE public.communities_community OWNER TO goodreads_clone_dev;

--
-- Name: communities_community_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.communities_community ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.communities_community_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: communities_community_members; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.communities_community_members (
    id bigint NOT NULL,
    community_id bigint NOT NULL,
    customuser_id bigint NOT NULL
);


ALTER TABLE public.communities_community_members OWNER TO goodreads_clone_dev;

--
-- Name: communities_community_members_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.communities_community_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.communities_community_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: communities_like; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.communities_like (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    post_id bigint NOT NULL
);


ALTER TABLE public.communities_like OWNER TO goodreads_clone_dev;

--
-- Name: communities_like_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.communities_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.communities_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: communities_post; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.communities_post (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    community_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.communities_post OWNER TO goodreads_clone_dev;

--
-- Name: communities_post_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.communities_post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.communities_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO goodreads_clone_dev;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO goodreads_clone_dev;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO goodreads_clone_dev;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO goodreads_clone_dev;

--
-- Name: shelves_shelf; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.shelves_shelf (
    id bigint NOT NULL,
    name character varying(128) NOT NULL,
    is_default boolean NOT NULL,
    user_id bigint NOT NULL,
    image character varying(100)
);


ALTER TABLE public.shelves_shelf OWNER TO goodreads_clone_dev;

--
-- Name: shelves_shelf_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.shelves_shelf ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shelves_shelf_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shelves_shelfbook; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.shelves_shelfbook (
    id bigint NOT NULL,
    book_id bigint NOT NULL,
    shelf_id bigint NOT NULL,
    current_page integer NOT NULL,
    date_added timestamp with time zone NOT NULL,
    notes text NOT NULL,
    date_finished timestamp with time zone,
    CONSTRAINT shelves_shelfbook_current_page_check CHECK ((current_page >= 0))
);


ALTER TABLE public.shelves_shelfbook OWNER TO goodreads_clone_dev;

--
-- Name: shelves_shelfbook_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.shelves_shelfbook ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shelves_shelfbook_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.users_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    bio text NOT NULL,
    image character varying(100) NOT NULL
);


ALTER TABLE public.users_customuser OWNER TO goodreads_clone_dev;

--
-- Name: users_customuser_groups; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.users_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_customuser_groups OWNER TO goodreads_clone_dev;

--
-- Name: users_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.users_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.users_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser_user_permissions; Type: TABLE; Schema: public; Owner: goodreads_clone_dev
--

CREATE TABLE public.users_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_customuser_user_permissions OWNER TO goodreads_clone_dev;

--
-- Name: users_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE public.users_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: books_author books_author_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_author
    ADD CONSTRAINT books_author_pkey PRIMARY KEY (id);


--
-- Name: books_author books_author_slug_key; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_author
    ADD CONSTRAINT books_author_slug_key UNIQUE (slug);


--
-- Name: books_book_genres books_book_genres_book_id_genre_id_4f4a9648_uniq; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_book_genres
    ADD CONSTRAINT books_book_genres_book_id_genre_id_4f4a9648_uniq UNIQUE (book_id, genre_id);


--
-- Name: books_book_genres books_book_genres_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_book_genres
    ADD CONSTRAINT books_book_genres_pkey PRIMARY KEY (id);


--
-- Name: books_book books_book_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_book
    ADD CONSTRAINT books_book_pkey PRIMARY KEY (id);


--
-- Name: books_book books_book_slug_key; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_book
    ADD CONSTRAINT books_book_slug_key UNIQUE (slug);


--
-- Name: books_book books_book_title_key; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_book
    ADD CONSTRAINT books_book_title_key UNIQUE (title);


--
-- Name: books_bookreview books_bookreview_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_bookreview
    ADD CONSTRAINT books_bookreview_pkey PRIMARY KEY (id);


--
-- Name: books_bookreview books_bookreview_user_id_book_id_3eac4b62_uniq; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_bookreview
    ADD CONSTRAINT books_bookreview_user_id_book_id_3eac4b62_uniq UNIQUE (user_id, book_id);


--
-- Name: books_genre books_genre_name_key; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_genre
    ADD CONSTRAINT books_genre_name_key UNIQUE (name);


--
-- Name: books_genre books_genre_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_genre
    ADD CONSTRAINT books_genre_pkey PRIMARY KEY (id);


--
-- Name: communities_comment communities_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_comment
    ADD CONSTRAINT communities_comment_pkey PRIMARY KEY (id);


--
-- Name: communities_community_members communities_community_me_community_id_customuser__1e75b0df_uniq; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_community_members
    ADD CONSTRAINT communities_community_me_community_id_customuser__1e75b0df_uniq UNIQUE (community_id, customuser_id);


--
-- Name: communities_community_members communities_community_members_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_community_members
    ADD CONSTRAINT communities_community_members_pkey PRIMARY KEY (id);


--
-- Name: communities_community communities_community_name_key; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_community
    ADD CONSTRAINT communities_community_name_key UNIQUE (name);


--
-- Name: communities_community communities_community_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_community
    ADD CONSTRAINT communities_community_pkey PRIMARY KEY (id);


--
-- Name: communities_like communities_like_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_like
    ADD CONSTRAINT communities_like_pkey PRIMARY KEY (id);


--
-- Name: communities_post communities_post_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_post
    ADD CONSTRAINT communities_post_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: shelves_shelf shelves_shelf_name_user_id_5f90e172_uniq; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.shelves_shelf
    ADD CONSTRAINT shelves_shelf_name_user_id_5f90e172_uniq UNIQUE (name, user_id);


--
-- Name: shelves_shelf shelves_shelf_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.shelves_shelf
    ADD CONSTRAINT shelves_shelf_pkey PRIMARY KEY (id);


--
-- Name: shelves_shelfbook shelves_shelfbook_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.shelves_shelfbook
    ADD CONSTRAINT shelves_shelfbook_pkey PRIMARY KEY (id);


--
-- Name: shelves_shelfbook shelves_shelfbook_shelf_id_book_id_b8af8563_uniq; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.shelves_shelfbook
    ADD CONSTRAINT shelves_shelfbook_shelf_id_book_id_b8af8563_uniq UNIQUE (shelf_id, book_id);


--
-- Name: communities_like unique_like_per_user_post; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_like
    ADD CONSTRAINT unique_like_per_user_post UNIQUE (post_id, user_id);


--
-- Name: users_customuser users_customuser_email_key; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_email_key UNIQUE (email);


--
-- Name: users_customuser_groups users_customuser_groups_customuser_id_group_id_76b619e3_uniq; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_customuser_id_group_id_76b619e3_uniq UNIQUE (customuser_id, group_id);


--
-- Name: users_customuser_groups users_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: users_customuser users_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_pkey PRIMARY KEY (id);


--
-- Name: users_customuser_user_permissions users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_user_pe_customuser_id_permission_7a7debf6_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: users_customuser_user_permissions users_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_customuser users_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: books_autho_name_5aec2d_idx; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_autho_name_5aec2d_idx ON public.books_author USING btree (name);


--
-- Name: books_autho_slug_b44f85_idx; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_autho_slug_b44f85_idx ON public.books_author USING btree (slug);


--
-- Name: books_author_slug_4c74843f_like; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_author_slug_4c74843f_like ON public.books_author USING btree (slug varchar_pattern_ops);


--
-- Name: books_book_author__709385_idx; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_book_author__709385_idx ON public.books_book USING btree (author_id);


--
-- Name: books_book_author_id_8b91747b; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_book_author_id_8b91747b ON public.books_book USING btree (author_id);


--
-- Name: books_book_genres_book_id_ffd9e72b; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_book_genres_book_id_ffd9e72b ON public.books_book_genres USING btree (book_id);


--
-- Name: books_book_genres_genre_id_899cd1a0; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_book_genres_genre_id_899cd1a0 ON public.books_book_genres USING btree (genre_id);


--
-- Name: books_book_slug_a38a79a6_like; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_book_slug_a38a79a6_like ON public.books_book USING btree (slug varchar_pattern_ops);


--
-- Name: books_book_slug_ca552e_idx; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_book_slug_ca552e_idx ON public.books_book USING btree (slug);


--
-- Name: books_book_title_be31d1ef_like; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_book_title_be31d1ef_like ON public.books_book USING btree (title varchar_pattern_ops);


--
-- Name: books_book_title_d3218d_idx; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_book_title_d3218d_idx ON public.books_book USING btree (title);


--
-- Name: books_bookr_user_id_e526f9_idx; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_bookr_user_id_e526f9_idx ON public.books_bookreview USING btree (user_id, book_id);


--
-- Name: books_bookreview_book_id_9c5fb3f1; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_bookreview_book_id_9c5fb3f1 ON public.books_bookreview USING btree (book_id);


--
-- Name: books_bookreview_user_id_a5746a0f; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_bookreview_user_id_a5746a0f ON public.books_bookreview USING btree (user_id);


--
-- Name: books_genre_name_27aecb_idx; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_genre_name_27aecb_idx ON public.books_genre USING btree (name);


--
-- Name: books_genre_name_b6ee53e9_like; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX books_genre_name_b6ee53e9_like ON public.books_genre USING btree (name varchar_pattern_ops);


--
-- Name: communities_comment_post_id_d0c53ca7; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX communities_comment_post_id_d0c53ca7 ON public.communities_comment USING btree (post_id);


--
-- Name: communities_comment_user_id_ee1f09c9; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX communities_comment_user_id_ee1f09c9 ON public.communities_comment USING btree (user_id);


--
-- Name: communities_community_members_community_id_f5c4f11d; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX communities_community_members_community_id_f5c4f11d ON public.communities_community_members USING btree (community_id);


--
-- Name: communities_community_members_customuser_id_c5851829; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX communities_community_members_customuser_id_c5851829 ON public.communities_community_members USING btree (customuser_id);


--
-- Name: communities_community_name_4dedcb1a_like; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX communities_community_name_4dedcb1a_like ON public.communities_community USING btree (name varchar_pattern_ops);


--
-- Name: communities_community_owner_id_15a7d936; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX communities_community_owner_id_15a7d936 ON public.communities_community USING btree (owner_id);


--
-- Name: communities_like_post_id_667ccf7e; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX communities_like_post_id_667ccf7e ON public.communities_like USING btree (post_id);


--
-- Name: communities_like_user_id_0ef24ed6; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX communities_like_user_id_0ef24ed6 ON public.communities_like USING btree (user_id);


--
-- Name: communities_post_community_id_7d7b8cf5; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX communities_post_community_id_7d7b8cf5 ON public.communities_post USING btree (community_id);


--
-- Name: communities_post_user_id_91c3d7b0; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX communities_post_user_id_91c3d7b0 ON public.communities_post USING btree (user_id);


--
-- Name: communities_user_id_37fd73_idx; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX communities_user_id_37fd73_idx ON public.communities_like USING btree (user_id, post_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: shelves_she_name_3d5126_idx; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX shelves_she_name_3d5126_idx ON public.shelves_shelf USING btree (name, user_id);


--
-- Name: shelves_she_shelf_i_dd77ec_idx; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX shelves_she_shelf_i_dd77ec_idx ON public.shelves_shelfbook USING btree (shelf_id, book_id);


--
-- Name: shelves_shelf_user_id_3b6c4a0f; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX shelves_shelf_user_id_3b6c4a0f ON public.shelves_shelf USING btree (user_id);


--
-- Name: shelves_shelfbook_book_id_033d1284; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX shelves_shelfbook_book_id_033d1284 ON public.shelves_shelfbook USING btree (book_id);


--
-- Name: shelves_shelfbook_shelf_id_9879fbc6; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX shelves_shelfbook_shelf_id_9879fbc6 ON public.shelves_shelfbook USING btree (shelf_id);


--
-- Name: users_custo_email_c80f75_idx; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX users_custo_email_c80f75_idx ON public.users_customuser USING btree (email);


--
-- Name: users_custo_usernam_a8ad03_idx; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX users_custo_usernam_a8ad03_idx ON public.users_customuser USING btree (username);


--
-- Name: users_customuser_email_6445acef_like; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX users_customuser_email_6445acef_like ON public.users_customuser USING btree (email varchar_pattern_ops);


--
-- Name: users_customuser_groups_customuser_id_958147bf; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX users_customuser_groups_customuser_id_958147bf ON public.users_customuser_groups USING btree (customuser_id);


--
-- Name: users_customuser_groups_group_id_01390b14; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX users_customuser_groups_group_id_01390b14 ON public.users_customuser_groups USING btree (group_id);


--
-- Name: users_customuser_user_permissions_customuser_id_5771478b; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX users_customuser_user_permissions_customuser_id_5771478b ON public.users_customuser_user_permissions USING btree (customuser_id);


--
-- Name: users_customuser_user_permissions_permission_id_baaa2f74; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX users_customuser_user_permissions_permission_id_baaa2f74 ON public.users_customuser_user_permissions USING btree (permission_id);


--
-- Name: users_customuser_username_80452fdf_like; Type: INDEX; Schema: public; Owner: goodreads_clone_dev
--

CREATE INDEX users_customuser_username_80452fdf_like ON public.users_customuser USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: books_book books_book_author_id_8b91747b_fk_books_author_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_book
    ADD CONSTRAINT books_book_author_id_8b91747b_fk_books_author_id FOREIGN KEY (author_id) REFERENCES public.books_author(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: books_book_genres books_book_genres_book_id_ffd9e72b_fk_books_book_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_book_genres
    ADD CONSTRAINT books_book_genres_book_id_ffd9e72b_fk_books_book_id FOREIGN KEY (book_id) REFERENCES public.books_book(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: books_book_genres books_book_genres_genre_id_899cd1a0_fk_books_genre_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_book_genres
    ADD CONSTRAINT books_book_genres_genre_id_899cd1a0_fk_books_genre_id FOREIGN KEY (genre_id) REFERENCES public.books_genre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: books_bookreview books_bookreview_book_id_9c5fb3f1_fk_books_book_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_bookreview
    ADD CONSTRAINT books_bookreview_book_id_9c5fb3f1_fk_books_book_id FOREIGN KEY (book_id) REFERENCES public.books_book(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: books_bookreview books_bookreview_user_id_a5746a0f_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.books_bookreview
    ADD CONSTRAINT books_bookreview_user_id_a5746a0f_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: communities_comment communities_comment_post_id_d0c53ca7_fk_communities_post_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_comment
    ADD CONSTRAINT communities_comment_post_id_d0c53ca7_fk_communities_post_id FOREIGN KEY (post_id) REFERENCES public.communities_post(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: communities_comment communities_comment_user_id_ee1f09c9_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_comment
    ADD CONSTRAINT communities_comment_user_id_ee1f09c9_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: communities_community_members communities_communit_community_id_f5c4f11d_fk_communiti; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_community_members
    ADD CONSTRAINT communities_communit_community_id_f5c4f11d_fk_communiti FOREIGN KEY (community_id) REFERENCES public.communities_community(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: communities_community_members communities_communit_customuser_id_c5851829_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_community_members
    ADD CONSTRAINT communities_communit_customuser_id_c5851829_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: communities_community communities_community_owner_id_15a7d936_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_community
    ADD CONSTRAINT communities_community_owner_id_15a7d936_fk_users_customuser_id FOREIGN KEY (owner_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: communities_like communities_like_post_id_667ccf7e_fk_communities_post_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_like
    ADD CONSTRAINT communities_like_post_id_667ccf7e_fk_communities_post_id FOREIGN KEY (post_id) REFERENCES public.communities_post(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: communities_like communities_like_user_id_0ef24ed6_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_like
    ADD CONSTRAINT communities_like_user_id_0ef24ed6_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: communities_post communities_post_community_id_7d7b8cf5_fk_communiti; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_post
    ADD CONSTRAINT communities_post_community_id_7d7b8cf5_fk_communiti FOREIGN KEY (community_id) REFERENCES public.communities_community(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: communities_post communities_post_user_id_91c3d7b0_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.communities_post
    ADD CONSTRAINT communities_post_user_id_91c3d7b0_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shelves_shelf shelves_shelf_user_id_3b6c4a0f_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.shelves_shelf
    ADD CONSTRAINT shelves_shelf_user_id_3b6c4a0f_fk_users_customuser_id FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shelves_shelfbook shelves_shelfbook_book_id_033d1284_fk_books_book_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.shelves_shelfbook
    ADD CONSTRAINT shelves_shelfbook_book_id_033d1284_fk_books_book_id FOREIGN KEY (book_id) REFERENCES public.books_book(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shelves_shelfbook shelves_shelfbook_shelf_id_9879fbc6_fk_shelves_shelf_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.shelves_shelfbook
    ADD CONSTRAINT shelves_shelfbook_shelf_id_9879fbc6_fk_shelves_shelf_id FOREIGN KEY (shelf_id) REFERENCES public.shelves_shelf(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_groups users_customuser_gro_customuser_id_958147bf_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_gro_customuser_id_958147bf_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_groups users_customuser_groups_group_id_01390b14_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.users_customuser_groups
    ADD CONSTRAINT users_customuser_groups_group_id_01390b14_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_user_permissions users_customuser_use_customuser_id_5771478b_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_use_customuser_id_5771478b_fk_users_cus FOREIGN KEY (customuser_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_customuser_user_permissions users_customuser_use_permission_id_baaa2f74_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: goodreads_clone_dev
--

ALTER TABLE ONLY public.users_customuser_user_permissions
    ADD CONSTRAINT users_customuser_use_permission_id_baaa2f74_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

