# Generated by Django 5.1.4 on 2024-12-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=128)),
                ('publication_date', models.DateField()),
                ('isbn', models.CharField(max_length=13)),
                ('pages', models.IntegerField()),
                ('cover', models.ImageField(default='default_book.png', upload_to='covers/')),
                ('buy_link', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-added_date'],
                'indexes': [models.Index(fields=['title'], name='books_book_title_d3218d_idx')],
            },
        ),
    ]
