# Generated by Django 5.1.4 on 2025-01-09 17:42
import books.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('birth_date', models.DateField(validators=[books.models.validate_future_date])),
                ('death_date', models.DateField(blank=True, null=True, validators=[books.models.validate_future_date, books.models.validate_death_date])),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(default='default_author.png', upload_to='authors_pics/')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='books_autho_name_5aec2d_idx'), models.Index(fields=['slug'], name='books_autho_slug_b44f85_idx')],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='books_autho_name_5aec2d_idx'), models.Index(fields=['slug'], name='books_autho_slug_b44f85_idx')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('buy_link', models.URLField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('pages', models.PositiveIntegerField()),
                ('publication_date', models.DateField(validators=[books.models.validate_future_date])),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(default='default_book.png', upload_to='covers/')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.author')),
            ],
            options={
                'ordering': ['-added_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'book'], name='books_bookr_user_id_e526f9_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='books_book_title_d3218d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='books_book_author__709385_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug'], name='books_book_slug_ca552e_idx'),
        ),
    ]
