# Generated by Django 5.1.4 on 2024-12-28 23:22

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(validators=[books.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.DateField(blank=True, null=True, validators=[books.models.validate_future_date, books.models.validate_death_date]),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(validators=[books.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['slug'], name='books_autho_slug_b44f85_idx'),
        ),
    ]
