# Generated by Django 5.1.4 on 2025-01-09 17:43

import django.db.models.deletion
import shelves.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, help_text='Cover image for the shelf', null=True, upload_to=shelves.models.shelf_image_upload_to)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShelfBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelves.shelf')),
            ],
        ),
        migrations.AddIndex(
            model_name='shelf',
            index=models.Index(fields=['name', 'user'], name='shelves_she_name_3d5126_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shelf',
            unique_together={('name', 'user')},
        ),
        migrations.AddIndex(
            model_name='shelfbook',
            index=models.Index(fields=['shelf', 'book'], name='shelves_she_shelf_i_dd77ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shelfbook',
            unique_together={('shelf', 'book')},
        ),
    ]
