# Generated by Django 5.1.4 on 2024-12-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfbook',
            name='current_page',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
