# Generated by Django 5.1.4 on 2024-12-28 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0003_shelfbook_current_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfbook',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelfbook',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
