# Generated by Django 5.1.4 on 2025-01-02 01:30

import shelves.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0005_shelfbook_date_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for the shelf', null=True, upload_to=shelves.models.shelf_image_upload_to),
        ),
    ]
